# api-web/values.yaml
replicaCount: 3

image:
  repository: tuanquang1811/vdt-midterm-web
  tag: v1
  pullPolicy: IfNotPresent

service:
  name: vdt-web
  type: NodePort
  ports:
    http:
      port: 80
      targetPort: 80
      nodePort: 30002
    metrics:
      port: 9100
      targetPort: 9100
      nodePort: 30004
  labels:
    app: vdt-web
prometheusNodeExporter:
  enabled: true
  image:
    repository: prom/node-exporter
    tag: latest
  ports:
    metrics: 9100